<?php

use App\Application\Accounts\Countries;

/*
 * A20: contract-fixtures/profile/countries.json, generated by scripts/gen-countries.php, is the
 * one list the server validator and the app's picker read.
 */

uses(Tests\TestCase::class);

/** @return list<array{code: string, name: string}> */
function countryRows(): array
{
    return json_decode((string) file_get_contents(dirname(__DIR__, 3).'/contract-fixtures/profile/countries.json'), true, flags: JSON_THROW_ON_ERROR);
}

it('lists unique two-letter upper-case codes with names', function () {
    $codes = array_column(countryRows(), 'code');

    expect($codes)->toHaveCount(count(array_unique($codes)));
    foreach (countryRows() as $row) {
        expect($row['code'])->toMatch('/^[A-Z]{2}$/')
            ->and(trim($row['name']))->not->toBe('');
    }
    expect($codes)->toContain('GH')->toContain('XK');
});

it('leaves out CLDR codes that are not countries', function () {
    expect(array_intersect(array_column(countryRows(), 'code'), ['AC', 'CP', 'CQ', 'DG', 'EA', 'EU', 'EZ', 'IC', 'TA', 'UN', 'XA', 'XB', 'ZZ', 'QO']))->toBe([]);
});

it('is the list the validator reads', function () {
    expect(array_keys(Countries::all()))->toEqualCanonicalizing(array_column(countryRows(), 'code'))
        ->and(Countries::isCode('GH'))->toBeTrue()
        ->and(Countries::isCode('gh'))->toBeFalse()
        ->and(Countries::isCode('EU'))->toBeFalse();
});
