<?php

namespace Tests\Support;

use App\Domain\Calendar\LocalDate;
use App\Domain\Habit\HabitTypeRegistry;
use App\Domain\Period\PeriodEngine;

/**
 * contract-fixtures/domain/schedule.json (Phase 3.2a): due-ness per local date, from the PHP
 * reference (HabitSchedule + PeriodEngine), so the Dart port of HabitSchedule answers the same.
 * Rows: [date, definition_version | null, active, eligible, due, period_key | null].
 */
final class ScheduleCases
{
    public static function path(): string
    {
        return dirname(__DIR__, 3).'/contract-fixtures/domain/schedule.json';
    }

    public static function encode(): string
    {
        $json = json_encode(self::fixture(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR)."\n";
        $scalar = '(?:"[^"]*"|true|false|null|-?\d+)';

        return (string) preg_replace_callback(
            '/\[\s*'.$scalar.'(?:\s*,\s*'.$scalar.')*\s*\]/',
            fn (array $m) => '['.trim((string) preg_replace('/\s*,\s*/', ', ', trim($m[0], "[] \n"))).']',
            $json,
        );
    }

    /** @return array<string, mixed> */
    public static function fixture(): array
    {
        return [
            'kind' => 'schedule',
            'suites' => ['php', 'dart'],
            'description' => 'Due-ness per local date: the governing definition version, active range, eligibility and whether the date belongs to a period (daily, weekdays, interval: the date itself; weekly_count: an active day of a week that is due, A28). Zero-length dates are never due (A30). Generated by api/tests/Support/generate_schedule.php from the PHP reference.',
            'rows' => '[date, definition_version, active, eligible, due, period_key]',
            'cases' => array_map(self::evaluate(...), self::seeds()),
        ];
    }

    /**
     * @param  array<string, mixed>  $case
     * @return array<string, mixed>
     */
    private static function evaluate(array $case): array
    {
        $types = HabitTypeRegistry::withBuiltins();
        // As a consumer reads it: the file's {} configs decode to arrays.
        $decoded = json_decode(json_encode($case, JSON_THROW_ON_ERROR), true, 512, JSON_THROW_ON_ERROR);
        $schedule = DomainFixtures::schedule($decoded['habit'], $types);
        $timeline = DomainFixtures::timeline($decoded['calendar']);
        $from = LocalDate::fromString($case['from']);
        $to = LocalDate::fromString($case['to']);
        $keys = [];
        foreach ((new PeriodEngine($types))->periods($schedule, $from, $to, $timeline) as $period) {
            foreach ($period->activeDates as $date) {
                $keys[$date->toString()] = $period->key;
            }
        }
        $rows = [];
        for ($date = $from; ! $date->isAfter($to); $date = $date->addDays(1)) {
            $key = $keys[$date->toString()] ?? null;
            $rows[] = [
                $date->toString(),
                $schedule->versionOn($date)?->version,
                $schedule->isActive($date),
                $schedule->isEligible($date),
                $key !== null,
                $key,
            ];
        }

        return [...$case, 'rows' => $rows];
    }

    /** @return list<array<string, mixed>> */
    private static function seeds(): array
    {
        $la = [['effective_at' => '2026-01-01T00:00:00Z', 'timezone' => 'America/Los_Angeles', 'day_start_offset_minutes' => 0]];
        $habit = fn (string $id, array $definitions, array $ranges) => [
            'id' => $id, 'name' => 'Habit', 'category' => 'health',
            'definitions' => $definitions, 'active_ranges' => $ranges, 'logs' => (object) [],
        ];
        $def = fn (int $v, string $from, string $type, array $config) => [
            'version' => $v, 'effective_date' => $from, 'type' => 'binary', 'target' => 1, 'unit' => null,
            'frequency_type' => $type, 'frequency_config' => (object) $config,
        ];
        $open = fn (string $from) => [['starts_on' => $from, 'ends_before' => null]];

        return [
            [
                'name' => 'daily from 1 May: nothing before the start',
                'calendar' => $la,
                'habit' => $habit('01970000-0000-7000-8000-0000000000b1', [$def(1, '2026-05-01', 'daily', [])], $open('2026-05-01')),
                'from' => '2026-04-29', 'to' => '2026-05-04',
            ],
            [
                'name' => 'weekdays Mon, Wed, Fri',
                'calendar' => $la,
                'habit' => $habit('01970000-0000-7000-8000-0000000000b2', [$def(1, '2026-05-01', 'weekdays', ['days' => [1, 3, 5]])], $open('2026-05-01')),
                'from' => '2026-05-04', 'to' => '2026-05-10',
            ],
            [
                'name' => 'every 3 days from the anchor',
                'calendar' => $la,
                'habit' => $habit('01970000-0000-7000-8000-0000000000b3', [$def(1, '2026-05-02', 'interval', ['every_n_days' => 3, 'anchor_date' => '2026-05-02'])], $open('2026-05-02')),
                'from' => '2026-05-01', 'to' => '2026-05-09',
            ],
            [
                'name' => 'weekly_count 3: two active days in the first week are not due, a full week is (A28)',
                'calendar' => $la,
                'habit' => $habit('01970000-0000-7000-8000-0000000000b4', [$def(1, '2026-05-09', 'weekly_count', ['count' => 3])], $open('2026-05-09')),
                'from' => '2026-05-04', 'to' => '2026-05-17',
            ],
            [
                'name' => 'a new definition (Tue, Thu) governs from its effective date',
                'calendar' => $la,
                'habit' => $habit('01970000-0000-7000-8000-0000000000b5', [
                    $def(1, '2026-05-01', 'daily', []),
                    $def(2, '2026-05-11', 'weekdays', ['days' => [2, 4]]),
                ], $open('2026-05-01')),
                'from' => '2026-05-08', 'to' => '2026-05-15',
            ],
            [
                'name' => 'an archived gap is never due',
                'calendar' => $la,
                'habit' => $habit('01970000-0000-7000-8000-0000000000b6', [$def(1, '2026-05-01', 'daily', [])], [
                    ['starts_on' => '2026-05-01', 'ends_before' => '2026-05-04'],
                    ['starts_on' => '2026-05-07', 'ends_before' => null],
                ]),
                'from' => '2026-05-02', 'to' => '2026-05-08',
            ],
            [
                'name' => 'a zero-length date (Pago_Pago to Auckland skips 11 March) is never due',
                'calendar' => [
                    ['effective_at' => '2026-01-01T00:00:00Z', 'timezone' => 'Pacific/Pago_Pago', 'day_start_offset_minutes' => 0],
                    ['effective_at' => '2026-03-11T11:00:00Z', 'timezone' => 'Pacific/Auckland', 'day_start_offset_minutes' => 0],
                ],
                'habit' => $habit('01970000-0000-7000-8000-0000000000b7', [$def(1, '2026-03-09', 'daily', [])], $open('2026-03-09')),
                'from' => '2026-03-09', 'to' => '2026-03-13',
            ],
        ];
    }
}
